remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: Yashovardhan Srivastava.
description: A genius, shy and broke bloke.
permalink: /404.html
lsi: false
safe: true
logo: /profile-pic.png
