theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  
title: Yashovardhan Srivastava
description: A genius, shy and broke bloke.
permalink: /404.html
lsi: false
safe: true
logo: /profile-pic.png
