remote_theme: aterenin/minima-reboot
title: Yashovardhan Srivastava
description: A genius, shy and broke bloke.
permalink: /404.html
lsi: false
safe: true
logo: /profile-pic.png
google_analytics: G-ERR9VSKKLD
footer_icons:
- username: yash-srivastava19
  url: https://github.com/yash-srivastava19
  icon: icon-github.svg

- username: Yaaaaaashhh
  url: https://twitter.com/Yaaaaaashhh
  icon: icon-twitter.svg  
