remote_theme: poole/lanyon
plugins:
- jekyll-remote-theme
title: Yashovardhan Srivastava.
description: A genius, shy and broke bloke.
permalink: /404.html
lsi: false
safe: true
logo: /profile-pic.png
